version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - sistema-entregas

volumes:
  database:

networks:
  sistema-entregas:
    driver: bridge
