services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: unicad-sistemas-entrega
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - unicad-network
    command: >
      sh -c "npx prisma migrate dev && npm run dev"

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: leonardo
      POSTGRES_PASSWORD: junior
      POSTGRES_DB: unicad
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - unicad-network

volumes:
  postgres-data:

networks:
  unicad-network:
    driver: bridge
