services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: unicad-sistemas-entrega
    container_name: unicad-sistemas-entrega
    depends_on:
      - postgres
    networks:
      - unicad-network
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate dev && npm run dev"

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - unicad-network
    env_file:
      - .env

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - nginx-data:/var/lib/nginx
    networks:
      - unicad-network

volumes:
  postgres-data:
  letsencrypt:
  nginx-data:

networks:
  unicad-network:
    driver: bridge
